# coding: utf-8

"""
    APIs RISKAMERICA

    A continuación les presentamos la documentación las **APIs** **de** **RiskAmerica**, el cual es un servicio pagado ofrecido por RiskAmerica que se contrata por separado a nuestras otras ofertas de software.  Algunas consideraciones que debe tener al momento de usar las APIs: - El APIKEY o Token lo puede conseguir solicitándolo al equipo comercial de RiskAmerica - El request necesita ser enviado con el header **Accept:** **application/json** para que responda en formato **JSON** (de no ser enviado con esto se responderá en formato **XML**) - Todos los Servicios son **REST** y sus parametros pueden ser enviados tanto en **POST** como **GET** - El uso de las APIs puede llevar un cobro asociado según se pacte en el acuerdo comercial, por lo que le recomendamos ser cuidadosos en el uso de éstas para evitar sobre-cargos innecesarios. - RiskAmerica funciona con un mecanismo de **WhiteList** **de** **IPs** para las consultas de las API. Para habilitar o modificar la lista de IPs permitidas debe contactarse al mail **contacto@riskamerica.com**.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import riam_api_client
from riam_api_client.api.fondos_api import FondosApi  # noqa: E501
from riam_api_client.rest import ApiException


class TestFondosApi(unittest.TestCase):
    """FondosApi unit test stubs"""

    def setUp(self):
        self.api = FondosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fondos_datos_cuota_get_fecha(self):
        """Test case for fondos_datos_cuota_get_fecha

        Obtiene los registros de datos cuota para todos los fondos para la fecha consultada.  # noqa: E501
        """
        pass

    def test_fondos_datos_cuota_get_serie(self):
        """Test case for fondos_datos_cuota_get_serie

        Obtiene los registros de datos cuota para todos los fondos para la serie consultada.  # noqa: E501
        """
        pass

    def test_fondos_informacion_get(self):
        """Test case for fondos_informacion_get

        Obtiene la información de un fondo y sus series.  # noqa: E501
        """
        pass

    def test_fondos_reprocesos_get_periodo(self):
        """Test case for fondos_reprocesos_get_periodo

        Obtiene los reprocesos de los datos cuota que han ocurrido en un periodo de tiempo.  # noqa: E501
        """
        pass

    def test_fondos_reprocesos_get_serie(self):
        """Test case for fondos_reprocesos_get_serie

        Obtiene los reprocesos de los datos cuota para una serie particular.  # noqa: E501
        """
        pass

    def test_fondos_retornos_ajustados_get_fecha(self):
        """Test case for fondos_retornos_ajustados_get_fecha

        Obtiene los registros de retornos del valor cuota ajustados por remuneración para todos los fondos para la fecha consultada.  # noqa: E501
        """
        pass

    def test_fondos_retornos_ajustados_get_serie(self):
        """Test case for fondos_retornos_ajustados_get_serie

        Obtiene los registros de retornos del valor cuota ajustados por remuneración para la serie consultada para la fecha consultada.  # noqa: E501
        """
        pass

    def test_fondos_retornos_get_fecha(self):
        """Test case for fondos_retornos_get_fecha

        Obtiene los registros de retornos del valor cuota para todos los fondos en la fecha consultada.  # noqa: E501
        """
        pass

    def test_fondos_retornos_get_serie(self):
        """Test case for fondos_retornos_get_serie

        Obtiene los registros de retornos del valor cuota para la serie consultada.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
