# coding: utf-8

"""
    APIs RISKAMERICA

    A continuación les presentamos la documentación las **APIs** **de** **RiskAmerica**, el cual es un servicio pagado ofrecido por RiskAmerica que se contrata por separado a nuestras otras ofertas de software.  Algunas consideraciones que debe tener al momento de usar las APIs: - El APIKEY o Token lo puede conseguir solicitándolo al equipo comercial de RiskAmerica - El request necesita ser enviado con el header **Accept:** **application/json** para que responda en formato **JSON** (de no ser enviado con esto se responderá en formato **XML**) - Todos los Servicios son **REST** y sus parametros pueden ser enviados tanto en **POST** como **GET** - El uso de las APIs puede llevar un cobro asociado según se pacte en el acuerdo comercial, por lo que le recomendamos ser cuidadosos en el uso de éstas para evitar sobre-cargos innecesarios. - RiskAmerica funciona con un mecanismo de **WhiteList** **de** **IPs** para las consultas de las API. Para habilitar o modificar la lista de IPs permitidas debe contactarse al mail **contacto@riskamerica.com**.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
# Importing related models
from .inline_response20028_clasificacion import InlineResponse20028Clasificacion




class InlineResponse20028Message(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fecha': 'date',
        'clasificacion': 'InlineResponse20028Clasificacion'
    }

    attribute_map = {
        'fecha': 'Fecha',
        'clasificacion': 'Clasificacion'
    }

    def __init__(self, fecha=None, clasificacion=None):  # noqa: E501
        """InlineResponse20028Message - a model defined in Swagger"""  # noqa: E501
        self._fecha = None
        self._clasificacion = None
        self.discriminator = None
        if fecha is not None:
            self.fecha = fecha
        if clasificacion is not None:
            self.clasificacion = clasificacion

    @property
    def fecha(self):
        """Gets the fecha of this InlineResponse20028Message.  # noqa: E501

        :return: The fecha of this InlineResponse20028Message.  # noqa: E501
        :rtype: date
        """
        return self._fecha

    @fecha.setter
    def fecha(self, fecha):
        """Sets the fecha of this InlineResponse20028Message.


        :param fecha: The fecha of this InlineResponse20028Message.  # noqa: E501
        :type: date
        """

        self._fecha = fecha

    @property
    def clasificacion(self):
        """Gets the clasificacion of this InlineResponse20028Message.  # noqa: E501

        :return: The clasificacion of this InlineResponse20028Message.  # noqa: E501
        :rtype: InlineResponse20028Clasificacion
        """
        return self._clasificacion

    @clasificacion.setter
    def clasificacion(self, clasificacion):
        """Sets the clasificacion of this InlineResponse20028Message.


        :param clasificacion: The clasificacion of this InlineResponse20028Message.  # noqa: E501
        :type: InlineResponse20028Clasificacion
        """

        self._clasificacion = clasificacion

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20028Message, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20028Message):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
