# coding: utf-8

"""
    APIs RISKAMERICA

    A continuación les presentamos la documentación las **APIs** **de** **RiskAmerica**, el cual es un servicio pagado ofrecido por RiskAmerica que se contrata por separado a nuestras otras ofertas de software.  Algunas consideraciones que debe tener al momento de usar las APIs: - El APIKEY o Token lo puede conseguir solicitándolo al equipo comercial de RiskAmerica - El request necesita ser enviado con el header **Accept:** **application/json** para que responda en formato **JSON** (de no ser enviado con esto se responderá en formato **XML**) - Todos los Servicios son **REST** y sus parametros pueden ser enviados tanto en **POST** como **GET** - El uso de las APIs puede llevar un cobro asociado según se pacte en el acuerdo comercial, por lo que le recomendamos ser cuidadosos en el uso de éstas para evitar sobre-cargos innecesarios. - RiskAmerica funciona con un mecanismo de **WhiteList** **de** **IPs** para las consultas de las API. Para habilitar o modificar la lista de IPs permitidas debe contactarse al mail **contacto@riskamerica.com**. - En caso de usar **Python** como lenguaje de programación puede visitar nuestro SDK disponible en [https://github.com/RiskAmerica/api-client-python](https://github.com/RiskAmerica/api-client-python) .  - En caso de usar otros lenguajes de programación puede usar el proyecto [https://github.com/swagger-api/swagger-codegen/tree/3.0.0](https://github.com/swagger-api/swagger-codegen/tree/3.0.0) para generar su propio SDK a partir del archivo [openapi.json](https://ra-public-files.s3-sa-east-1.amazonaws.com/wide-public/riam-api/openapi.json) . - Todas las APIs funcionan exclusivamente bajo el protocolo HTTPS usando TLS 1.2 o 1.3   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
# Importing related models




class InlineResponse20029Message(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fecha': 'date',
        'tipo': 'str',
        'monto': 'float',
        'porcentaje_saldo': 'float'
    }

    attribute_map = {
        'fecha': 'fecha',
        'tipo': 'tipo',
        'monto': 'monto',
        'porcentaje_saldo': 'porcentajeSaldo'
    }

    def __init__(self, fecha=None, tipo=None, monto=None, porcentaje_saldo=None):  # noqa: E501
        """InlineResponse20029Message - a model defined in Swagger"""  # noqa: E501
        self._fecha = None
        self._tipo = None
        self._monto = None
        self._porcentaje_saldo = None
        self.discriminator = None
        if fecha is not None:
            self.fecha = fecha
        if tipo is not None:
            self.tipo = tipo
        if monto is not None:
            self.monto = monto
        if porcentaje_saldo is not None:
            self.porcentaje_saldo = porcentaje_saldo

    @property
    def fecha(self):
        """Gets the fecha of this InlineResponse20029Message.  # noqa: E501
        Fecha del prepago  # noqa: E501

        :return: The fecha of this InlineResponse20029Message.  # noqa: E501
        :rtype: date
        """
        return self._fecha

    @fecha.setter
    def fecha(self, fecha):
        """Sets the fecha of this InlineResponse20029Message.

        Fecha del prepago  # noqa: E501

        :param fecha: The fecha of this InlineResponse20029Message.  # noqa: E501
        :type: date
        """

        self._fecha = fecha

    @property
    def tipo(self):
        """Gets the tipo of this InlineResponse20029Message.  # noqa: E501
        Tipo de prepago, puede ser TOTAL  o PARCIAL  # noqa: E501

        :return: The tipo of this InlineResponse20029Message.  # noqa: E501
        :rtype: str
        """
        return self._tipo

    @tipo.setter
    def tipo(self, tipo):
        """Sets the tipo of this InlineResponse20029Message.

        Tipo de prepago, puede ser TOTAL  o PARCIAL  # noqa: E501

        :param tipo: The tipo of this InlineResponse20029Message.  # noqa: E501
        :type: str
        """

        self._tipo = tipo

    @property
    def monto(self):
        """Gets the monto of this InlineResponse20029Message.  # noqa: E501
        Monto prepagado  # noqa: E501

        :return: The monto of this InlineResponse20029Message.  # noqa: E501
        :rtype: float
        """
        return self._monto

    @monto.setter
    def monto(self, monto):
        """Sets the monto of this InlineResponse20029Message.

        Monto prepagado  # noqa: E501

        :param monto: The monto of this InlineResponse20029Message.  # noqa: E501
        :type: float
        """

        self._monto = monto

    @property
    def porcentaje_saldo(self):
        """Gets the porcentaje_saldo of this InlineResponse20029Message.  # noqa: E501
        Monto prepagado como porcentaje del saldo  # noqa: E501

        :return: The porcentaje_saldo of this InlineResponse20029Message.  # noqa: E501
        :rtype: float
        """
        return self._porcentaje_saldo

    @porcentaje_saldo.setter
    def porcentaje_saldo(self, porcentaje_saldo):
        """Sets the porcentaje_saldo of this InlineResponse20029Message.

        Monto prepagado como porcentaje del saldo  # noqa: E501

        :param porcentaje_saldo: The porcentaje_saldo of this InlineResponse20029Message.  # noqa: E501
        :type: float
        """

        self._porcentaje_saldo = porcentaje_saldo

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20029Message, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20029Message):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
