# coding: utf-8

"""
    APIs RISKAMERICA

    A continuación les presentamos la documentación las **APIs** **de** **RiskAmerica**, el cual es un servicio pagado ofrecido por RiskAmerica que se contrata por separado a nuestras otras ofertas de software.  Algunas consideraciones que debe tener al momento de usar las APIs: - El APIKEY o Token lo puede conseguir solicitándolo al equipo comercial de RiskAmerica - El request necesita ser enviado con el header **Accept:** **application/json** para que responda en formato **JSON** (de no ser enviado con esto se responderá en formato **XML**) - Todos los Servicios son **REST** y sus parametros pueden ser enviados tanto en **POST** como **GET** - El uso de las APIs puede llevar un cobro asociado según se pacte en el acuerdo comercial, por lo que le recomendamos ser cuidadosos en el uso de éstas para evitar sobre-cargos innecesarios. - RiskAmerica funciona con un mecanismo de **WhiteList** **de** **IPs** para las consultas de las API. Para habilitar o modificar la lista de IPs permitidas debe contactarse al mail **contacto@riskamerica.com**. - En caso de usar **Python** como lenguaje de programación puede visitar nuestro SDK disponible en [https://github.com/RiskAmerica/api-client-python](https://github.com/RiskAmerica/api-client-python) .  - En caso de usar otros lenguajes de programación puede usar el proyecto [https://github.com/swagger-api/swagger-codegen/tree/3.0.0](https://github.com/swagger-api/swagger-codegen/tree/3.0.0) para generar su propio SDK a partir del archivo [openapi.json](https://ra-public-files.s3-sa-east-1.amazonaws.com/wide-public/riam-api/openapi.json) . - Todas las APIs funcionan exclusivamente bajo el protocolo HTTPS usando TLS 1.2 o 1.3   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six
# Model imports
from . import InlineResponse20010
from . import InlineResponse20010
from . import InlineResponse20011
# Importing for doctring purposes
# Api Client
from riam_api_client.api_client import ApiClient


class FondosCarterasApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def fondos_carteras_carteras_get_fecha(self, fecha, tipo_fondo, **kwargs):  # noqa: E501
        """Obtiene la composición de cartera mensual para los fondos de un tipo en el mes de la fecha consultada.  # noqa: E501

        La respuesta está paginada por fondo (keyset sobre el rut) para acotar el volumen: cada llamada devuelve a lo más {pageSize} fondos, ordenados por rut ascendente. Para recorrer todo el universo, el cliente repite la llamada pasando en {rutDesde} el mayor rut recibido en la página anterior, y se detiene cuando una página vuelve vacía. La cartera de un fondo nunca se parte entre páginas.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.fondos_carteras_carteras_get_fecha(fecha, tipo_fondo, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param date fecha: Fecha a consultar (se usa el mes y año) (required)
        :param str tipo_fondo: Tipo de fondo: CFM o CFI (required)
        :param str categoria_aafm: Nombre de la categoría AAFM para filtrar (solo aplica a CFM). Si se omite, se retornan todos los fondos del tipo.
        :param int rut_desde: Paginación: rut del último fondo recibido en la página anterior. Se devuelven los fondos con rut mayor. Omitir (o 0) para la primera página.
        :param int page_size: Cantidad de fondos por página (default 50, máximo 100).
        :return: InlineResponse20010
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InlineResponse20010 | multiprocessing.pool.ApplyResult
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.fondos_carteras_carteras_get_fecha_with_http_info(fecha, tipo_fondo, **kwargs)  # noqa: E501
        else:
            (data) = self.fondos_carteras_carteras_get_fecha_with_http_info(fecha, tipo_fondo, **kwargs)  # noqa: E501
            return data

    def fondos_carteras_carteras_get_fecha_with_http_info(self, fecha, tipo_fondo, **kwargs):  # noqa: E501
        """Obtiene la composición de cartera mensual para los fondos de un tipo en el mes de la fecha consultada.  # noqa: E501

        La respuesta está paginada por fondo (keyset sobre el rut) para acotar el volumen: cada llamada devuelve a lo más {pageSize} fondos, ordenados por rut ascendente. Para recorrer todo el universo, el cliente repite la llamada pasando en {rutDesde} el mayor rut recibido en la página anterior, y se detiene cuando una página vuelve vacía. La cartera de un fondo nunca se parte entre páginas.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.fondos_carteras_carteras_get_fecha_with_http_info(fecha, tipo_fondo, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param date fecha: Fecha a consultar (se usa el mes y año) (required)
        :param str tipo_fondo: Tipo de fondo: CFM o CFI (required)
        :param str categoria_aafm: Nombre de la categoría AAFM para filtrar (solo aplica a CFM). Si se omite, se retornan todos los fondos del tipo.
        :param int rut_desde: Paginación: rut del último fondo recibido en la página anterior. Se devuelven los fondos con rut mayor. Omitir (o 0) para la primera página.
        :param int page_size: Cantidad de fondos por página (default 50, máximo 100).
        :return: InlineResponse20010
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InlineResponse20010 | multiprocessing.pool.ApplyResult
        """

        all_params = ['fecha', 'tipo_fondo', 'categoria_aafm', 'rut_desde', 'page_size']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method fondos_carteras_carteras_get_fecha" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'fecha' is set
        if ('fecha' not in params or
                params['fecha'] is None):
            raise ValueError("Missing the required parameter `fecha` when calling `fondos_carteras_carteras_get_fecha`")  # noqa: E501
        # verify the required parameter 'tipo_fondo' is set
        if ('tipo_fondo' not in params or
                params['tipo_fondo'] is None):
            raise ValueError("Missing the required parameter `tipo_fondo` when calling `fondos_carteras_carteras_get_fecha`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'fecha' in params:
            query_params.append(('fecha', params['fecha']))  # noqa: E501
        if 'tipo_fondo' in params:
            query_params.append(('tipoFondo', params['tipo_fondo']))  # noqa: E501
        if 'categoria_aafm' in params:
            query_params.append(('categoriaAAFM', params['categoria_aafm']))  # noqa: E501
        if 'rut_desde' in params:
            query_params.append(('rutDesde', params['rut_desde']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/Outputs/Generic/Fondos/Carteras/getFecha', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse20010',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def fondos_carteras_carteras_get_fondo(self, fecha, rut, **kwargs):  # noqa: E501
        """Obtiene la composición de cartera mensual de un fondo específico en el mes de la fecha consultada.  # noqa: E501

        Obtiene la composición de cartera mensual de un fondo específico en el mes de la fecha consultada.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.fondos_carteras_carteras_get_fondo(fecha, rut, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param date fecha: Fecha a consultar (se usa el mes y año) (required)
        :param int rut: Rut del Fondo (sin dígito verificador) (required)
        :return: InlineResponse20010
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InlineResponse20010 | multiprocessing.pool.ApplyResult
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.fondos_carteras_carteras_get_fondo_with_http_info(fecha, rut, **kwargs)  # noqa: E501
        else:
            (data) = self.fondos_carteras_carteras_get_fondo_with_http_info(fecha, rut, **kwargs)  # noqa: E501
            return data

    def fondos_carteras_carteras_get_fondo_with_http_info(self, fecha, rut, **kwargs):  # noqa: E501
        """Obtiene la composición de cartera mensual de un fondo específico en el mes de la fecha consultada.  # noqa: E501

        Obtiene la composición de cartera mensual de un fondo específico en el mes de la fecha consultada.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.fondos_carteras_carteras_get_fondo_with_http_info(fecha, rut, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param date fecha: Fecha a consultar (se usa el mes y año) (required)
        :param int rut: Rut del Fondo (sin dígito verificador) (required)
        :return: InlineResponse20010
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InlineResponse20010 | multiprocessing.pool.ApplyResult
        """

        all_params = ['fecha', 'rut']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method fondos_carteras_carteras_get_fondo" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'fecha' is set
        if ('fecha' not in params or
                params['fecha'] is None):
            raise ValueError("Missing the required parameter `fecha` when calling `fondos_carteras_carteras_get_fondo`")  # noqa: E501
        # verify the required parameter 'rut' is set
        if ('rut' not in params or
                params['rut'] is None):
            raise ValueError("Missing the required parameter `rut` when calling `fondos_carteras_carteras_get_fondo`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'fecha' in params:
            query_params.append(('fecha', params['fecha']))  # noqa: E501
        if 'rut' in params:
            query_params.append(('rut', params['rut']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/Outputs/Generic/Fondos/Carteras/getFondo', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse20010',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def fondos_carteras_carteras_get_ultima_fecha(self, tipo_fondo, **kwargs):  # noqa: E501
        """Obtiene la última fecha de cartera disponible para un tipo de fondo.  # noqa: E501

        Obtiene la última fecha de cartera disponible para un tipo de fondo.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.fondos_carteras_carteras_get_ultima_fecha(tipo_fondo, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tipo_fondo: Tipo de fondo: CFM o CFI (required)
        :return: InlineResponse20011
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InlineResponse20011 | multiprocessing.pool.ApplyResult
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.fondos_carteras_carteras_get_ultima_fecha_with_http_info(tipo_fondo, **kwargs)  # noqa: E501
        else:
            (data) = self.fondos_carteras_carteras_get_ultima_fecha_with_http_info(tipo_fondo, **kwargs)  # noqa: E501
            return data

    def fondos_carteras_carteras_get_ultima_fecha_with_http_info(self, tipo_fondo, **kwargs):  # noqa: E501
        """Obtiene la última fecha de cartera disponible para un tipo de fondo.  # noqa: E501

        Obtiene la última fecha de cartera disponible para un tipo de fondo.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.fondos_carteras_carteras_get_ultima_fecha_with_http_info(tipo_fondo, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tipo_fondo: Tipo de fondo: CFM o CFI (required)
        :return: InlineResponse20011
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InlineResponse20011 | multiprocessing.pool.ApplyResult
        """

        all_params = ['tipo_fondo']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method fondos_carteras_carteras_get_ultima_fecha" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'tipo_fondo' is set
        if ('tipo_fondo' not in params or
                params['tipo_fondo'] is None):
            raise ValueError("Missing the required parameter `tipo_fondo` when calling `fondos_carteras_carteras_get_ultima_fecha`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'tipo_fondo' in params:
            query_params.append(('tipoFondo', params['tipo_fondo']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/Outputs/Generic/Fondos/Carteras/getUltimaFecha', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse20011',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
